name: sample_clean_architecture
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  provider: ^6.0.4
  bloc: any
  flutter_bloc: ^8.1.1
  auto_route: ^5.0.2

dev_dependencies:
  build_runner:
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  auto_route_generator: ^5.0.3

flutter: 
  uses-material-design: true

